### ISSUE TITLE
这个项目能服务器单边使用么？

### ISSUE THREAD

**Issue by wanliofficial** [luckydrq/tcp-net#2]
大佬，感谢贡献这么好的项目，我最近也是做一个需要用TCP做长连接的后端通讯服务，从前端转过来的，其实对TCP啥也不懂，唯一优势就是比较懂Node.js吧。我要处理的那个场景是设备端（有人GPRS模块）传过来的十六进制数据，在服务端解析成相应数据，然后存入MySQL中，同时服务端要维持和设备端的连接，因为用户在前端可以通过后端向指定设备发送远程命令。

我们大概有500多台设备在全国，所以，对后端TCP服务要求非常稳定。我曾用原生的Node.js里面的net模块创建一个TCP Server，做压力测试时，就是模拟10000台设备同时和TCP Server长连接，发现Node.js在运行30分钟后，V8引擎抛出一个内存溢出错误，上网查，很多人都说要复用TCP连接，就这么一句话，我实在是一头雾水，不知道如何用代码复用TCP，因为时间紧迫，暂时用Python的多线程特性搭一个TCP Server了，但是我本意还是想用Node.js，因为都说Node.js就是为了高并发的网络应用场景而生的，据说单机扛住10W+Socket连接不是事，然后我就在网上搜，就找到您这个项目。

看了您这个项目，如下问题：
①发现客户端也要安装Node.js库，那我这个项目是不是没办法使用您这个库了；
②我在做压力测试时，1W TCP长连接导致V8抛出内存溢出错误，是什么原因；
③在Node.js原生net模块，如何用代码实现多路复用；
④如何编写可靠稳定长连接支持至少1W+的TCP服务；

**Comment by wanliofficial** [comment]
![微信截图_20190717234953](https://user-images.githubusercontent.com/11154968/61390598-aa562a80-a8ed-11e9-9ec6-499150170d7a.png)
附图

**Comment by wanliofficial** [comment]
![微信截图_20190717234953](https://user-images.githubusercontent.com/11154968/61390640-c0fc8180-a8ed-11e9-9006-18aec7948266.png)
附图

**Comment by luckydrq** [comment]
你好，TCP长连接是需要客户端和服务端约定的，例如连接怎么保活，数据编解码使用什么方式以及数据协议是怎样的等等。如果客户端不想保持长连接，例如超过30秒它就要主动断开连接，那么长连接也无法维持下去。因此，这个项目是无法单边使用的。

关于你提的4个问题，有的有些宽泛，我尝试回答一下：
>①发现客户端也要安装Node.js库，那我这个项目是不是没办法使用您这个库了；

客户端不一定要用Node.js，但是如果用其他语言，需要实现上面所说的“约定”，语言不是关键，约定才是。因此，如果服务端用了我的库，最好客户端也用，这样成本是最低的。

>②我在做压力测试时，1W TCP长连接导致V8抛出内存溢出错误，是什么原因；

对于内存溢出（OOM）的问题，通常我们是要进行堆快照分析的，推荐使用阿里云的[alinode](https://www.aliyun.com/product/nodejs?spm=a2c4g.11174283.2.1.5e0d30b189uk7k)产品或者直接使用[heapdump](https://github.com/bnoordhuis/node-heapdump)这个库来生成堆快照，然后在Chrome Devtools里就可以分析了。

>③在Node.js原生net模块，如何用代码实现多路复用；

这个问题可以直接看我的代码，我也是用原生的net模块来实现的，知乎的文章里其实也有写怎么进行多路复用，可以仔细看下“粘包”、“通信模型”和“协议”那几个章节。

>④如何编写可靠稳定长连接支持至少1W+的TCP服务；

这个问题就有些泛了，需要从硬件和软件两个方面来说：

硬件方面，TCP长连接由于连接是一直存在的，比较消耗服务端的内存，如果并发请求很大，也比较消耗CPU（编解码、解析解析）。所以服务器硬件配置一定要跟上，需要做压测来确定一个合适的值。

软件方面，也就是代码设计层面，对于连接的管理是非常重要的。比如让一段时间内空闲的连接先断开回收，以减轻服务器压力，这里可以设计一些心跳机制。又例如连接因异常（现实的网络环境是错综复杂的）断开后，能够自动重连，重连后又能接着做刚才未完成的工作，这里还涉及到会话恢复的问题。另外，如果数据特别重要，可以使用一些“多写”的设计，即服务端向多个客户端发送一份相同的数据，用于备份。总得来说，网络环境是比较复杂的，我遇到的场景还没有你的复杂，因此还需要你再探索一下，有问题欢迎交流 :)

**Comment by fengdexunmi** [comment]
@wanliofficial 你好，我也有类似的场景，想请问下你这边最后选择了什么方案，用了哪个开源库呢？
